### ISSUE TITLE
Restore native SSL provider

### ISSUE THREAD

**Issue by AndrewX192** [arcus-smart-home/arcushubos#14]
As part of the changes to 2.7.1/agent upgrade/java upgrade (so much has moved forward recently, it's not entirely clear), the agent can't load any of it's native SSL providers and defaults back to the JDK. For current use cases, this probably isn't a big deal, but presumably if the agent has a lot of data to send back/forth (e.g. if video streaming was enabled), then this could become a bottleneck:

```t
D1021 15:47:17.941 rker-1   c.i.agent.gateway.GatewayNetty] using jdk for gateway ssl provider: 
java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty-tcnative-linux-arm_32, netty-tcnative-linux-arm_32-fedora, netty-tcnative]
	at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:180)
	at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:403)
	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:85)
	at com.iris.agent.gateway.GatewayNetty.createSslProvider(GatewayNetty.java:77)
	at com.iris.agent.gateway.Gateway.start(Gateway.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.netflix.governator.lifecycle.warmup.WarmUpTask.warmUpObject(WarmUpTask.java:125)
	at com.netflix.governator.lifecycle.warmup.WarmUpTask.compute(WarmUpTask.java:98)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:1107)
	at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2046)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:390)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
	at com.netflix.governator.lifecycle.warmup.WarmUpTask.compute(WarmUpTask.java:93)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

(Note: this could easily be an arcusplatform task, will probably require a bit more triage)

**Comment by pcouto64** [comment]
Yeah, there are some binaries that need to be rebuilt when the underlying libraries (glibc? I forget) change.  Hmm, I'll have to dig back in my memory to recall how to do this...

**Comment by pcouto64** [comment]
Updated native libraries needed by the agent (libnetty-tcnative and libapr-1) due to recent underlying libary changes resulting from the Yocto upgrade to 2.7.1.  Added a recipe in the hubOS code to allow these binaries to be easily built when needed again in the future.
